name: 3001_pexel1109_car_T05_Iter100
manual_seed: 74831
mixed_precision: fp16
gradient_checkpointing: true

# dataset and data loader settings
datasets:
  type: SingleVideoPointDataset
  path: datasets/paper_evaluation/object/pexels_11095143_car/frames
  tap_path: datasets/paper_evaluation/object/pexels_11095143_car/TAP.pth
  prompt: a black car driving down a desert road
  num_frames: 16
  total_frames: 64
  video_transform:
    - { type: Resize, size: [448, 768]}
    - { type: ToTensor }
    - { type: Normalize, mean: [ 0.5 ], std: [ 0.5 ] }
  batch_size_per_gpu: 1
  dataset_enlarge_ratio: 100

models:
  unet:
    type: AnimateDiffUNet3DModel
    inference_config_path: options/model_cfg/inference.yml
    motion_module_path: experiments/pretrained_models/animatediff_motion_module/mm_sd_v14.ckpt
  adapter:
    type: SparsePointAdapter
    model_config_path: options/model_cfg/point_adapter.yml

# path
path:
  pretrained_model_path: experiments/pretrained_models/chilloutmix

# training settings
train:
  train_pipeline: VideoSwapTrainer

  optimizer:
    type: AdamW
    lr: !!float 5e-4
    weight_decay: 0.01
    betas: [ 0.9, 0.999 ]

  tune_cfg:
    drop_rate: 0.2
    min_timestep: 0.5
    loss_type: global

  lr_scheduler: constant
  total_iter: 100
  warmup_iter: 0

# validation settings
val:
  val_pipeline: VideoSwapPipeline
  save_type: video
  val_freq: 100
  editing_config:
    use_invertion_latents: True
    use_blend: true
    visualize_point: true
    guidance_scale: 7.5
    editing_prompts:
      car_to_porsche:
        replace: black car -> black <porsche1> <porsche2>
        lora_path: experiments/pretrained_models/ED-LoRA/object/8202_EDLoRA_porsche356a_Cmix_B2_Repeat300_nomask/models/edlora_model-latest.pth---0.7
        tap_path: ~  # for change shape
        select_point: [Right headlight, Right wheel, Right rear wheel]
      car_to_carA:
        replace: black car -> golden <carA1> <carA2> with black wing
        lora_path: experiments/pretrained_models/ED-LoRA/object/8201_EDLoRA_carA_Cmix_B2_Repeat300_nomask/models/edlora_model-latest.pth---1.0
        tap_path: ~
        select_point: [Right wheel, Right rear wheel]
        negative_prompt: dark, worst quality, low quality, deformed, distorted, disfigured, bad eyes, bad anatomy, disconnected limbs, wrong body proportions, low quality, worst quality, text, watermark, signatre, logo, illustration, painting, cartoons, ugly, easy_negative
    negative_prompt: worst quality, low quality, deformed, distorted, disfigured, bad eyes, bad anatomy, disconnected limbs, wrong body proportions, low quality, worst quality, text, watermark, signatre, logo, illustration, painting, cartoons, ugly, easy_negative
    num_inference_steps: 50
    t2i_guidance_scale: 0.2
    t2i_start: 0.0
    t2i_end: 0.5

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 100
