name: 1005_final_ss1015_T07_Iter50
manual_seed: 74831
mixed_precision: fp16
gradient_checkpointing: true

# dataset and data loader settings
datasets:
  type: SingleVideoPointDataset
  path: datasets/paper_evaluation/human/ss_1015684228_woman_walk/frames
  tap_path: datasets/paper_evaluation/human/ss_1015684228_woman_walk/TAP.pth
  prompt: a woman is walking in a forest with trees and grass in the background
  num_frames: 16
  total_frames: 48
  video_transform:
    - { type: Resize, size: [448, 768]}
    - { type: ToTensor }
    - { type: Normalize, mean: [ 0.5 ], std: [ 0.5 ] }
  batch_size_per_gpu: 1
  dataset_enlarge_ratio: 100

models:
  unet:
    type: AnimateDiffUNet3DModel
    inference_config_path: options/model_cfg/inference.yml
    motion_module_path: experiments/pretrained_models/animatediff_motion_module/mm_sd_v14.ckpt
  adapter:
    type: SparsePointAdapter
    model_config_path: options/model_cfg/point_adapter.yml

# path
path:
  pretrained_model_path: experiments/pretrained_models/chilloutmix
  pretrained_adapter_path: experiments/pretrained_models/VideoSwap_Model/human/1005_final_ss1015_T07_Iter50/models/models_50/adapter.pth

# training settings
train:
  train_pipeline: VideoSwapTrainer

  optimizer:
    type: AdamW
    lr: !!float 5e-4
    weight_decay: 0.01
    betas: [ 0.9, 0.999 ]

  tune_cfg:
    drop_rate: 0.2
    min_timestep: 0.7
    loss_type: global

  lr_scheduler: constant
  total_iter: 50
  warmup_iter: 0

# validation settings
val:
  val_pipeline: VideoSwapPipeline
  save_type: video
  val_freq: 50
  editing_config:
    use_invertion_latents: True
    use_blend: true
    guidance_scale: 7.5
    visualize_point: True
    editing_prompts:
      woman_to_batman:
        replace: woman -> black armored <batman1> <batman2>
        lora_path: experiments/pretrained_models/ED-LoRA/human/8104_EDLoRA_batmanv3_Cmix_B4_Repeat500_nomask/models/edlora_model-latest.pth---0.5
        tap_path: ~
        select_point: ~
      woman_to_ironman:
        replace: woman -> <ironman1> <ironman2> with chest light
        lora_path: experiments/pretrained_models/ED-LoRA/human/8105_EDLoRA_ironman_Cmix_B4_Repeat500_nomask/models/edlora_model-latest.pth---0.2
        tap_path: ~
        blend_cfg:
          cross_replace_steps: 0.2
          self_replace_steps: 0.2
        select_point: ~
      woman_to_thanos:
        replace: woman -> <thanos1> <thanos2>
        lora_path: experiments/pretrained_models/ED-LoRA/human/8103_EDLoRA_thanos_Cmix_B4_Repeat250/models/edlora_model-latest.pth---1.0
        tap_path: ~
        select_point: ~
        t2i_guidance_scale: 0.3
      woman_to_hermione_alpha07:
        replace: woman -> <hermione1> <hermione2>
        lora_path: experiments/pretrained_models/ED-LoRA/human/8102_EDLoRA_hermione_Cmix_B4_Repeat500/models/edlora_model-latest.pth---0.7
        tap_path: ~
        blend_cfg:
          cross_replace_steps: 0.5
          self_replace_steps: 0.5
        select_point: ~ # for remove points
        t2i_guidance_scale: 0.3
      woman_to_potter_alpha07:
        replace: woman -> <potter1> <potter2>
        lora_path: experiments/pretrained_models/ED-LoRA/human/8101_EDLoRA_potter_Cmix_B4_Repeat500/models/edlora_model-latest.pth---0.7
        tap_path: ~
        blend_cfg:
          cross_replace_steps: 0.5
          self_replace_steps: 0.5
        select_point: ~ # for remove points
        t2i_guidance_scale: 0.3
    negative_prompt: cartoon, anime, sketches, worst quality, low quality, deformed, distorted, disfigured, bad eyes, wrong lips, weird mouth, bad teeth, mutated hands and fingers, bad anatomy, wrong anatomy, amputation, extra limb, missing limb, floating limbs, disconnected limbs, mutation, ugly, disgusting, bad_pictures, negative_hand-neg
    num_inference_steps: 50
    t2i_guidance_scale: 0.5
    t2i_start: 0.0
    t2i_end: 0.3

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 50
